### ISSUE TITLE
Stata13 files cause problems

### ISSUE THREAD

**Issue by nilshg** [floswald/psidR#6]
As per [this stackoverflow thread](http://stackoverflow.com/questions/23899009/read-stata-13-file-in-r), `read.dta` does not support `dta` files for Stata versions >12, which can cause problems for users creating the .dta files with newer versions of Stata. 

Two things could solve this:
1. Use [read.dta13](http://radyakin.org/transfer/use13/use13.htm) where necessary (not sure whether this would help with Stata 14)
2. Add a note to the docs to inform users to save their .dta files using `saveold` in Stata

**Comment by floswald** [comment]
ha, that's a good point! point 1 will only kick the can down the road for another year (usually one stata format is incompatible for the next one).  i guess should add that note, or alternatively download directly. thanks for raising this!

**Comment by JanMarvin** [comment]
Hey, we have support for Stata 14 (format 118) in the testing branch of readstata13. Possibly wie realease this weekend. Though I haven't used psidR nor checked the code recently and can't say weather this is helpful for you.

**Comment by JanMarvin** [comment]
Plus we have support for all Stata dta formats foreign knows, plus a few I found along the way. This is in branch pre13. This might be in the release after the next.

**Comment by floswald** [comment]
Great thanks for chipping in - I'll take a look!

**Comment by floswald** [comment]
hey @JanMarvin, how can I determine what stata version file comes in? i.e. i want to test a file to avoid

    read.dta13("http://www.stata-press.com/data/r12/auto.dta")
    Error: First byte: Not a version 13 dta-file.

**Comment by JanMarvin** [comment]
Hey, our current implementation - e.g. the package that is on CRAN - only handles Stata 13 dta-files. Our branch "testing" is able to read Stata 14 dta-files as well (we will release this once we're happy with additional encoding stuff [should be soon]). Reading Stata 12 files is currently implemented in branch "pre13". This will be our next "testing" once we have released. (Everything should be working, but some things still need some love.)

While reading we do not specify a specific version. So if you want to read a Stata 12 dta-file this should work (just checked on Arch Linux; we only require a version when saving a dta-file). When reading  `readstata13::read.dta13` can be used as as drop in replacement for `foreign::read.dta`:

```R
# requires Rcpp and devtools
devtools::install_github("sjewo/readstata13", ref="pre13")
library("readstata13")
dd <- read.dta13("http://www.stata-press.com/data/r12/auto.dta")
```

The error you are seeing is caused by checking the first byte of a Stata dta-file. With version 13 Stata changed to an XML-like format and the first byte is "<" (of XML-like tag `<stata_dta>`). If the first byte isn't "<" we currently just stop. In branch "pre13" we restart reading the file and check for the "old" dta-file format. Although everything looks promising, I can't give an ETA.

**Comment by floswald** [comment]
i can only imagine how painful it is to tell one dta format from another (i guess they don't give you a nice place where to read that from.). 
can you ping me when you have made enough progress on that pre13 branch? thanks!

**Comment by JanMarvin** [comment]
Hey @floswald, since release 0.8 we support all documented Stata releases. Our current release is 0.8.1 and everything seems fine aka zero bugs were reported. Maybe you like to give it a try?
